config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :upload_csvs
  # get 'upload_csv/new'
  get 'home/index'
  # devise_for :users
  root 'upload_csvs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/upload_csv.rb
class UploadCsv < ApplicationRecord
  validates :csv_file, presence: true
  validates :users, presence: true
  mount_uploader :csv_file, AvatarUploader
  after_create :processed_csv, on: :create
  def processed_csv
    GenrateCsvJob.perform_later(self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[show edit update destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show; end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit; end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_student
    @student = Student.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def student_params
    params.require(:student).permit(:name, :url)
  end
end

app/controllers/upload_csvs_controller.rb
class UploadCsvsController < ApplicationController
  before_action :set_upload_csv, only: %i[show edit update destroy]
  require 'csv'
  require 'httparty'
  require 'nokogiri'
  # GET /upload_csvs
  # GET /upload_csvs.json
  def index
    @pagy, @upload_csvs = pagy(UploadCsv.all, page: params[:page], items: 5)
  end

  # GET /upload_csvs/1
  # GET /upload_csvs/1.json
  def show; end

  # GET /upload_csvs/new
  def new
    @upload_csv = UploadCsv.new
  end

  # GET /upload_csvs/1/edit
  def edit; end

  # POST /upload_csvs
  # POST /upload_csvs.json
  def create
    @upload_csv = params[:upload_csv] ? UploadCsv.new(upload_csv_params) : UploadCsv.new
    respond_to do |format|
      if @upload_csv.save
        format.html { redirect_to root_path, notice: 'Uploaded csv, we will let you know once that is processed and email will be deliver.' }
        format.json { render :show, status: :created, location: @upload_csv }
      else
        format.html { render :new }
        format.json { render json: @upload_csv.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /upload_csvs/1
  # PATCH/PUT /upload_csvs/1.json
  def update
    respond_to do |format|
      if @upload_csv.update(upload_csv_params)
        format.html { redirect_to @upload_csv, notice: 'Upload csv was successfully updated.' }
        format.json { render :show, status: :ok, location: @upload_csv }
      else
        format.html { render :edit }
        format.json { render json: @upload_csv.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /upload_csvs/1
  # DELETE /upload_csvs/1.json
  def destroy
    @upload_csv.destroy
    respond_to do |format|
      format.html { redirect_to upload_csvs_url, notice: 'Upload csv was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

    private

  # Use callbacks to share common setup or constraints between actions.
  def set_upload_csv
    @upload_csv = UploadCsv.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def upload_csv_params
    params.require(:upload_csv).permit(:csv_file, :generated_csv, users: [])
  end
  end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/upload_csv_helper.rb
module UploadCsvHelper
end

app/helpers/upload_csvs_helper.rb
module UploadCsvsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShahnawazTest</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>  
  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="/">Home</a>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">

        <li class="nav-item">   
          <%= link_to('Home', root_path, class: "nav-link") %>
        </li>
        <li class="nav-item">   
          <%= link_to('Upload CSV', new_upload_csv_path, class: "nav-link") %>
        </li>

      </ul>
    </div>
  </nav>
  <script type="text/javascript">
    <%  if notice.present?%>
    var message = "<%= notice %>";
    sweetAlert(message);
    <% end %>
    <%  if alert.present?%>
    var message = "<%= alert %>";
    sweetAlert(message);
    
    <% end %>
  </script>
  
  <%= yield %>
</body>
</html>

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_area :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.url.html_safe %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @student.url %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

app/views/upload_csvs/_form.html.erb
<div class="row">
  
  <%= bootstrap_form_with(model: upload_csv, local: true) do |form| %>
    <% if upload_csv.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(upload_csv.errors.count, "error") %> prohibited this upload_csv from being saved:</h2>

        <ul>
        <% upload_csv.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <select  class="js-searchable" name="upload_csv[users][]" multiple="multiple" style="width: 270px;">
    </select>
    <%= form.file_field :csv_file %>


    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    $(".js-searchable").select2({
      tags: true,
      placeholder: "Add multiple email Address only email allowed.",
      tokenSeparators: [','],
      createTag: function(term, data) {
          var value = term.term;
          if(validateEmail(value)) {
              return {
                id: value,
                text: value
              };
          }else
          return null;            
      }
    })

  })
  function validateEmail(email) {
    var re = /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
    return re.test(email);
}
</script>

app/views/upload_csvs/edit.html.erb
<div class="container">

  <h1>Editing Upload Csv</h1>

  <%= render 'form', upload_csv: @upload_csv %>

  <%= link_to 'Show', @upload_csv %> |
  <%= link_to 'Back', upload_csvs_path %>
</div>

app/views/upload_csvs/index.html.erb
<div class="container">

  <div class="row">
    <div class="col-sm-10 col-lg-10 col-md-10">

      <p id="notice"><%= notice %></p>

      <h1>Upload Csvs</h1>

      <table class="table table-striped">
        <thead>
          <tr>
            <th>Users</th>
            <th>Csv file</th>
            <th>Generated csv</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @upload_csvs.each do |upload_csv| %>
          <tr>
            <td><%= upload_csv.users %></td>
            <td><%= upload_csv.csv_file %></td>
            <td><%= upload_csv.generated_csv %></td>
            <td><%= link_to 'Show', upload_csv %></td>
            <td><%= link_to 'Edit', edit_upload_csv_path(upload_csv) %></td>
            <td><%= link_to 'Destroy', upload_csv, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= pagy_bootstrap_nav(@pagy).html_safe %>

      <br>

      <%= link_to 'New Upload Csv', new_upload_csv_path %>
    </div>
  </div>
</div>

app/views/upload_csvs/new.html.erb
<div class="container">

  <h1>New Upload Csv</h1>

  <%= render 'form', upload_csv: @upload_csv %>

  <%= link_to 'Back', upload_csvs_path %>
</div>

app/views/upload_csvs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Users:</strong>
  <%= @upload_csv.users %>
</p>

<p>
  <strong>Csv file:</strong>
  <%= @upload_csv.csv_file %>
</p>

<p>
  <strong>Generated csv:</strong>
  <%= @upload_csv.generated_csv %>
</p>

<%= link_to 'Edit', edit_upload_csv_path(@upload_csv) %> |
<%= link_to 'Back', upload_csvs_path %>